### ISSUE TITLE
Are we going to have mice mm39/GRCm39 database?

### ISSUE THREAD

**Issue by xinyixinyijiang** [aertslab/create_cisTarget_databases#43]
Hi cisTarget team, 

Thank you for your software!

I utilized GRCm39/mm39 to map my scRNAseq data, as the gene annotation for GRCm38/mm10 does not contain a gene of interest (the mutant gene in mice) that was discovered in recent years. I plan to apply pySCENIC to the data but noticed that no mm39 mice database is available. 

Could you kindly confirm whether there are plans to release a mice mm39/GRCm39 database in the near future?
Moreover, I would appreciate any insights you might have regarding potential problems/limitations I could have by using the mm10 databases provided for my data.

Thank you for your attention to my questions. 🙂

**Comment by ghuls** [comment]
Probably we will have mice mm39/GRCm39 database in the near future. Assuming that the gene that you are interested in was not renamed, the mm database will not be useful for you, otherwise you could look at old synonyms for your gene of interest and see if one of them appears in the mm10 database: https://www.informatics.jax.org/marker/

**Comment by ghuls** [comment]
yes, you should be able to use your gene expression matrix as input of pySCENIC (assuming that not too many gene names are changed), even if the assembly is different.
